version: '3.9'

services:
  java_app:
    container_name: java_app
    image: java-app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://java_db:3306/rest_api_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
    restart: always
    depends_on:
      java_db:
        condition: service_healthy
  java_db:
    container_name: java_db
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DB: rest_api_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10